"""Agregar campos de comercio al modelo Usuario

Revision ID: 4c49a6e8e0e2
Revises: 
Create Date: 2025-05-03 11:45:00.465391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c49a6e8e0e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_comercio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nombre_comercio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ya_registrado_en_mapa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ya_registrado_en_mapa')
        batch_op.drop_column('nombre_comercio')
        batch_op.drop_column('es_comercio')

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###
