"""Campo nuevo para donaciones.

Revision ID: 4d63c339f98a
Revises: 8f2129747432
Create Date: 2025-05-04 03:35:13.423833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d63c339f98a'
down_revision = '8f2129747432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dono', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('dono')

    # ### end Alembic commands ###
