"""Agregar campo banner_url a LugarSugerido

Revision ID: 8f2129747432
Revises: 75a955659125
Create Date: 2025-05-03 21:42:40.515334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2129747432'
down_revision = '75a955659125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lugar_sugerido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lugar_sugerido', schema=None) as batch_op:
        batch_op.drop_column('banner_url')

    # ### end Alembic commands ###
