"""Agregar campo publicidad_activa a usuarios.

Revision ID: ef4c83ab19f0
Revises: 4d63c339f98a
Create Date: 2025-05-04 03:59:44.431207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4c83ab19f0'
down_revision = '4d63c339f98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicidad_activa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('publicidad_activa')

    # ### end Alembic commands ###
